
GET http://localhost:3000

###
GET http://localhost:3000/rotas

###
GET http://localhost:3000/rotas/64eb9f341533c6dd81964935

###
POST http://localhost:3000/rotas
Content-Type: application/json

{
    "name": "teste rota 2",
    "source_id": "EkdBdi4gQnJhc2lsLCAxMDcwIC0gQ2VudHJvLCBCYWxuZcOhcmlvIENhbWJvcmnDuiAtIFNDLCA4ODMzMC0wNDUsIEJyYXNpbCIxEi8KFAoSCZVpbCj-ydiUEQoxoCKdCsDjEK4IKhQKEgljdoKwGrbYlBGWrWZN_x49Og",
    "destination_id": "ChIJmzuMsgG22JQR0oDwKEgQygA"
}

### mapas

### pegar o place_id
GET http://localhost:3000/lugares?texto=av brasil, 1070, balneário camboriú, sc

### outro lugar... próximo
GET http://localhost:3000/lugares?texto=rua 701, 66

### pegar direções entre 2 pontos
GET http://localhost:3000/direcoes?idOrigem=EkdBdi4gQnJhc2lsLCAxMDcwIC0gQ2VudHJvLCBCYWxuZcOhcmlvIENhbWJvcmnDuiAtIFNDLCA4ODMzMC0wNDUsIEJyYXNpbCIxEi8KFAoSCZVpbCj-ydiUEQoxoCKdCsDjEK4IKhQKEgljdoKwGrbYlBGWrWZN_x49Og&idDestino=ChIJmzuMsgG22JQR0oDwKEgQygA